### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by kediarbuz** [domon41c/Flixium-OS-ASM#1]
Я только что ее запустил на своем Xiaomi 87 Ultra Pro Max Super Giga+ 8G и твоя ОС пишет что "ослам ос юзать нельзя" Это что вообще такое? Я буду жаловаться и писать заяву на осла в суд Асляндии!!!!!

**Comment by kediarbuz** [comment]
Uploading 2_5204167368112089301.mp4…

Пруфы вот

**Comment by kediarbuz** [comment]
Ответьте на жалобу!!!!!!!

**Comment by domon41c** [comment]
0_0

**Comment by domon41c** [comment]
Извините, но ОС не может запускаться на ARM архитектурах и вообще на телефонах, пока-что только X86-64, покупайте ПК.

**Comment by kediarbuz** [comment]
А ВОТ ЕЩЕ НА МОЕМ АСУС ВИВА УЛЬТРАБУК 2023 CORE I9 GT210 AEROCOOL KCAS 1200W ПИШЫЫЫЫТ ТОЖЕ САМОЕ!!!!!

**Comment by kediarbuz** [comment]
ЧО ВЫ ЕГНОРИТЕ АДМИНЫ ОСЛЫ

**Comment by domon41c** [comment]
Попробуйте скомпилировать сами исходники в .iso или запустить на QEMU.

**Comment by kediarbuz** [comment]
НЕЕЕТ

**Comment by kediarbuz** [comment]
ВСЕ ДАЛЖНА РАБОТАТЬ ИЗ КАРОБКИ

**Comment by kediarbuz** [comment]
А ВЫ НУБВА НЕ ШАРИТЕ

**Comment by kediarbuz** [comment]
ЛУЧЩЕ БЫ РАЙЗЕН КУПИЛ БВ

**Comment by kediarbuz** [comment]
ЧТО ТОКОЕ ЙЕМУ

**Comment by kediarbuz** [comment]
Я ЗАПУСКАЮ ТОКА НА ВЕИИУАЛЬБОКС

**Comment by domon41c** [comment]
На виртуал бокс нельзя запускать ОС с .img расширением, попробуйте через QEMU, в скорем ОС будет и в .iso и ее можно будет записать на флешку.
